/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reto5.empleadosGUI;


import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import reto5.empleadosDAL.conexion;

/**
 *
 * @author alexis
 */
public class empleadosGUI extends javax.swing.JFrame {
    DefaultTableModel modelo;
    
    /**
     * Creates new form interfaz
     */
    public empleadosGUI() {
        initComponents();
        String[] titulos ={"ID_Lider","Nombre","Primer_Apellido","Ciudad_Residencia"};
        modelo = new DefaultTableModel(null,titulos);
        btlTable.setModel(modelo);
        
        
    }
    /**
     * Creates new form empleadosGUI
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btlTable = new javax.swing.JTable();
        btnprueba1 = new javax.swing.JButton();
        btnprueba2 = new javax.swing.JButton();
        btnprueba3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(btlTable);

        btnprueba1.setText("consulta1");
        btnprueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprueba1ActionPerformed(evt);
            }
        });

        btnprueba2.setText("consulta2");
        btnprueba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprueba2ActionPerformed(evt);
            }
        });

        btnprueba3.setText("consulta3");
        btnprueba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprueba3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnprueba1)
                .addGap(63, 63, 63)
                .addComponent(btnprueba2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnprueba3)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprueba1)
                    .addComponent(btnprueba2)
                    .addComponent(btnprueba3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprueba1ActionPerformed
        // TODO add your handling code here:
        mostrarDatos();
        
    }//GEN-LAST:event_btnprueba1ActionPerformed

    private void btnprueba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprueba2ActionPerformed
        // TODO add your handling code here:
        
        mostrarDatos2();
    }//GEN-LAST:event_btnprueba2ActionPerformed

    private void btnprueba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprueba3ActionPerformed
        // TODO add your handling code here:
         mostrarDatos3();
    }//GEN-LAST:event_btnprueba3ActionPerformed
    public void mostrarDatos(){
        
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
            
        }
        conexion objetoConexion = new conexion();
        try{
            ResultSet resultado = objetoConexion.consultarRegistros("SELECT * FROM Lider ORDER BY Ciudad_Residencia");
            while(resultado.next()){
                resultado.getString("ID_Lider");
                resultado.getString("Nombre");
                resultado.getString("Primer_Apellido");
                resultado.getString("Ciudad_Residencia");
                Object[] oUser = {resultado.getString("ID_Lider"),resultado.getString("Nombre"),resultado.getString("Primer_Apellido"),resultado.getString("Ciudad_Residencia")};
                modelo.addRow(oUser);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    public void mostrarDatos2(){
         
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objetoConexion = new conexion();
        try{
            ResultSet resultado = objetoConexion.consultarRegistros("SELECT ID_Proyecto,Constructora,Numero_Habitaciones,Ciudad FROM Proyecto WHERE Clasificacion = 'Casa Campestre' AND Ciudad = 'Santa Marta' OR Ciudad = 'Barranquilla' OR Ciudad = 'Cartagena'");
            while(resultado.next()){
                resultado.getString("ID_Proyecto");
                resultado.getString("Constructora");
                resultado.getString("Numero_Habitaciones");
                resultado.getString("Ciudad");
                Object[] oUser = {resultado.getString("ID_Proyecto"),resultado.getString("Constructora"),resultado.getString("Numero_Habitaciones"),resultado.getString("Ciudad")};
                modelo.addRow(oUser);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    public void mostrarDatos3(){
         
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objetoConexion = new conexion();
        try{
            ResultSet resultado = objetoConexion.consultarRegistros("SELECT c.ID_Compra ,a.Constructora , a.Banco_Vinculado FROM Proyecto a join Compra c on a.ID_Proyecto = c.ID_Proyecto WHERE a.Clasificacion = 'Casa Campestre' AND  c.Proveedor = 'Homecenter'");
            while(resultado.next()){
                resultado.getString("ID_Compra");
                resultado.getString("Constructora");
                resultado.getString("Banco_Vinculado");
                
                Object[] oUser = {resultado.getString("ID_Compra"),resultado.getString("Constructora"),resultado.getString("Banco_Vinculado")};
                modelo.addRow(oUser);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    /**
     * Creates new form interfaz
     */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleadosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlTable;
    private javax.swing.JButton btnprueba1;
    private javax.swing.JButton btnprueba2;
    private javax.swing.JButton btnprueba3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
