/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reto5.empleadosGUI;

import javax.swing.table.DefaultTableModel;
import reto5.empleadosDAL.conexion;
import java.sql.ResultSet;
/**
 *
 * @author alexis
 */
public class opcion1 extends javax.swing.JPanel {

    /**
     * Creates new form opcion2
     */
    DefaultTableModel modelo;
    
    public opcion1() {
        initComponents();
        initComponents();
        String[] titulos ={"ID_Lider","Nombre","Primer_Apellido","Ciudad_Residencia"};
        modelo = new DefaultTableModel(null,titulos);
        btlTable.setModel(modelo);
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        conexion objetoConexion = new conexion();
        try{
            ResultSet resultado = objetoConexion.consultarRegistros("SELECT * FROM Lider ORDER BY Ciudad_Residencia");
            while(resultado.next()){
                resultado.getString("ID_Lider");
                resultado.getString("Nombre");
                resultado.getString("Primer_Apellido");
                resultado.getString("Ciudad_Residencia");
                Object[] oUser = {resultado.getString("ID_Lider"),resultado.getString("Nombre"),resultado.getString("Primer_Apellido"),resultado.getString("Ciudad_Residencia")};
                modelo.addRow(oUser);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btlTable = new javax.swing.JTable();

        btlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        btlTable.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(btlTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
